theodo/scrumble

showcase/public/index.html
@nicgirault peux-tu checker la PR ?
=> Correct intransitive verb in index page

client/src/project/states/main/controller.coffee, client/src/project/states/main/view.jade
@nicgirault peux-tu checker la PR ?
ticket : https://trello.com/c/sfVuRfQp/262-etqu-je-vois-tous-les-projets-sur-la-page-de-selection-d-un-projet-groupe-par-organisation
=> Add organization grouping to project view

api/migrations/20160615094935-add-spreadsheet-in-organization.js, api/migrations/sqls/20160615094935-add-spreadsheet-in-organization-down.sql, api/migrations/sqls/20160615094935-add-spreadsheet-in-organization-up.sql, api/src/models/organization.json, client/src/organization/states/settings/view.jade
@nicgirault peux-tu checker la PR ? De ton côté je pense qu'il faut que tu fasses les migrations pour que ça fonctionne.
ticket : https://trello.com/c/cpmZyV4b/265-etqu-je-peux-sauvegarder-l-id-de-spreadsheet
=> Save spreadsheet id in organization page

client/src/project/states/main/style.less, client/src/project/states/main/view.jade
@nicgirault peux-tu reviewer ?
ticket : https://trello.com/c/zqNjOTFP/271-etqu-la-grid-list-est-responsive-je-vois-2-boards-par-ligne-sur-mobile-et-jusqu-a-6-sur-grand-ecran
=> Add responsivity to tiles in projects view

client/src/project/states/main/view.jade
@nicgirault peux-tu checker la PR? 
ticket : https://trello.com/c/WdUzg7Ei/274-etqu-je-peux-filtrer-la-liste-des-boards-sur-la-page-des-boards
=> Add filter text to projects page

client/src/project/states/main/view.jade
=> Change code indentation in jade file

client/src/indicators/directives/client-form/controller.coffee, client/src/indicators/directives/client-form/view.jade
@nicgirault peux-tu checker la PR ?
ticket : https://trello.com/c/rLLHb8hB/277-etqu-je-vois-un-bouton-de-sauvegarde-du-questionnaire-dans-la-spreadsheet
=> Add save in spreadsheet button

client/src/project/module.coffee, client/src/project/states/main/controller.coffee, docker-compose.dev.yml.dist, docker-compose.prod.yml.dist
#185 
Les tests passent en local :B
=> flush daily-report cache on project switch

client/src/problems/components/problems-list/directive.coffee, client/src/problems/components/problems-list/template.jade, client/src/problems/states/problem-list/controller.coffee, client/src/problems/states/problem-list/view.jade
[ETQU, je peux imprimer la liste des actions prises pour les problèmes de mon équipe](https://trello.com/c/kBhzdiPv/306-etqu-je-peux-imprimer-la-liste-des-actions-prises-pour-les-problemes)
Visuel MVP :
=> Added compact list of problems

client/src/problems/components/tag-input/style.less, client/src/problems/components/tag-input/template.jade
[Cédric a ajouté un seul tag et a cliqué sur save et le tag n'est pas sauvegardé](https://trello.com/c/UeJtWMXe/293-cedric-a-ajoute-un-seul-tag-et-a-clique-sur-save-et-le-tag-n-est-pas-sauvegarde)
=> Added help for tag creation

client/src/daily-report/states/template/view.jade
=> Fix typo Todat -> Today

api/migrations/20170227134826-Add.js, api/migrations/sqls/20170227134826-Add-down.sql, api/migrations/sqls/20170227134826-Add-up.sql, api/src/models/daily-report.coffee, api/src/models/daily-report.json
L'objectif est de collecter un peu des daily mails (dans l'idéal ~1000) afin de pouvoir faire du learning sur le contenu des mails.
Idée pour l'instant : 
* Génération automatique de problèmes & événements à partir des mots présents dans le daily mail (ex: Retour / retard / Félicitations)
=> Save all dailyReports for future data usage

api/src/models/scrumble-user.coffee
Authentication is now based on the Trello ID instead of the email.
See #202 
cc @yleflour, this should fix your issue
=> Fix logging in when you have changed your Trello email (fix #202)

Makefile, client/bower.json, client/src/common/config/routes.coffee, client/src/daily-report/directives/select-goals/controller.coffee, client/src/daily-report/services/cards.coffee, client/src/sprint/states/edit/view.jade, client/src/styles/app.less
Allow selection of multiple doing columns to easily find cards when writing daily
=> Multiple doing columns

client/src/daily-report/states/template/controller.coffee, client/src/daily-report/states/template/view.jade
This code should prompt the user with a confirmation dialog when leaving the Daily Mail page to prevent lose of all the work done so far
=> Confirmation on daily modif

README.md, client/src/daily-report/services/report-builder.coffee
Si le sprint termine dans moins de 2 jours et que le gap est inférieur à 0, alors l'email du CTO est automatiquement ajoutée dans la liste des destinataires du daily mail (en CC)
=> ETQCTO, je reçois une copie du daily mail si le sprint risque d'être KO

.env.example, .gitignore, README.md, client/esbuild.config.js, client/package-lock.json, client/package.json, docker-compose.yaml
- miss : add `TRELLO_KEY` and `GOOGLE_CLIENT_ID` in heroku env variables
=> feat: add env file to store local env variables

client/package-lock.json, client/package.json, client/src/common/services/dynamic-fields.coffee, client/src/daily-report/services/report-builder.coffee, client/src/daily-report/states/template/controller.coffee, client/src/daily-report/states/template/style.less, client/src/daily-report/states/template/view.html
=> feat: add a section to upload images for mail templating

client/public/icons/document-file-download.svg, client/src/app.coffee, client/src/daily-report/states/template/controller.coffee, client/src/daily-report/states/template/style.less, client/src/daily-report/states/template/view.html
- improve design and UX
- add preview of uploaded imae
- prevent user to upload another type of file than image
- cut filename if too long
=> feat: improve image input design and cut file name when too long

client/src/daily-report/services/report-builder.coffee
=> Revert "fix: add bdc in cid only if {bdc} is matched in sprint progress"
